GET http://localhost:8080/api/spacecraft/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJyb2dlci5oZXJtYW4iLCJpYXQiOjE3MTUxMzcyODgsImV4cCI6MTcxNTE3MzI4OH0.ElGBAEGsj65CtMBJz6Lz7YYSQOtrFEzBsnjxge1VedlIYkMhdH7WmTnaN_g_Ftiq

###
GET http://localhost:8080/api/spacecraft/list-page?page=0&size=5


###
GET http://localhost:8080/api/spacecraft/search?name=Hola&page=0&size=5

###
GET http://localhost:8080/api/spacecraft/search?name=Ho&page=0&size=10

###
GET http://localhost:8080/api/spacecraft/2

###

GET http://localhost:8080/api/spacecraft/2
###

GET http://localhost:8080/api/spacecraft/500
###revisar el retorno de código http

GET http://localhost:8080/api/spacecraft/aaa
###revisar el retorno de código http

###/http://localhost:8080/spacecraft/{modelId}/{planetId}"
POST http://localhost:8080/api/spacecraft/1/1
Content-Type: application/json

{
    "name": "Hola 742",
    "credit": 8525,
    "totalTime": 1324 
}

###
PUT http://localhost:8080/api/spacecraft
Content-Type: application/json

{
    "id": 11,
    "name": "Equipo dinamita",
    "credit": 125,
    "totalTime": 55
}

###@PatchMapping("/player/{id}/planet/{planetId}")
PATCH http://localhost:8080/api/spacecraft/player/1/planet/4

###
DELETE http://localhost:8080/api/spacecraft/14


###
PATCH http://localhost:8080/api/spacecraft/10/name

Anastasio

### http://localhost:8080/{spacecraftid}/model/
GET http://localhost:8080/api/spacecraft/2/model

### http://localhost:8080/{spacecraftid}/planetId"
GET http://localhost:8080/api/spacecraft/2/planet

### http://localhost:8080/{spacecraftid}/actualInventory"
GET http://localhost:8080/api/spacecraft/2/actualInventory

### http://localhost:8080/{spacecraftid}/inventory" para obtener los productos
GET http://localhost:8080/api/spacecraft/2/inventory

### http://localhost:8080/{spacecraftid}/spacecrafts" para obtener los productos
GET http://localhost:8080/api/spacecraft/1/spacecrafts
